CREATE TABLE public.app_user_connections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, connector_id text NOT NULL, connection_key_ciphertext text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,connector_id));
GRANT ALL ON public.app_user_connections TO service_role;
ALTER TABLE public.app_user_connections ENABLE ROW LEVEL SECURITY;
CREATE TABLE public.thread_attachments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, thread_id uuid NOT NULL REFERENCES public.threads(id) ON DELETE CASCADE, filename text NOT NULL, object_path text NOT NULL UNIQUE, media_type text NOT NULL, size_bytes bigint NOT NULL CHECK(size_bytes > 0 AND size_bytes <= 10485760), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, DELETE ON public.thread_attachments TO authenticated;
GRANT ALL ON public.thread_attachments TO service_role;
ALTER TABLE public.thread_attachments ENABLE ROW LEVEL SECURITY;
CREATE POLICY attachment_read ON public.thread_attachments FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY attachment_insert ON public.thread_attachments FOR INSERT TO authenticated WITH CHECK(user_id = auth.uid() AND EXISTS (SELECT 1 FROM public.threads WHERE id = thread_id AND user_id = auth.uid()));
CREATE POLICY attachment_delete ON public.thread_attachments FOR DELETE TO authenticated USING(user_id = auth.uid());
CREATE POLICY private_chat_file_read ON storage.objects FOR SELECT TO authenticated USING(bucket_id = 'chat-attachments' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY private_chat_file_insert ON storage.objects FOR INSERT TO authenticated WITH CHECK(bucket_id = 'chat-attachments' AND (storage.foldername(name))[1] = auth.uid()::text AND EXISTS(SELECT 1 FROM public.threads WHERE id::text = (storage.foldername(name))[2] AND user_id = auth.uid()));
CREATE POLICY private_chat_file_delete ON storage.objects FOR DELETE TO authenticated USING(bucket_id = 'chat-attachments' AND (storage.foldername(name))[1] = auth.uid()::text);