import {createFileRoute} from '@tanstack/react-router';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useServerFn} from '@tanstack/react-start';
import {Github,Folder,FileCode,GitCommitHorizontal,RefreshCw,Unplug,ArrowRight,LockKeyhole} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {IntegrationShell} from '@/components/IntegrationShell';
import {browseGithub,startGithubConnect,completeGithubConnection,disconnectGithub,type GithubItem} from '@/lib/github.functions';
import {EXAMPLE_REPO,EXAMPLE_FILES,EXAMPLE_CONTENT,EXAMPLE_COMMITS} from '@/lib/github-example';

export const Route=createFileRoute('/_authenticated/github')({head:()=>({meta:[{title:'مستودعات GitHub — AzCodex'},{name:'description',content:'استعراض مستودعاتك وملفاتك وسجل الالتزامات مع مثال صيانة العزب.'},{property:'og:title',content:'مستودعات GitHub — AzCodex'},{property:'og:description',content:'مستودعات وملفات وسجل تغييرات GitHub في AzCodex.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:GithubPage});

function waitForOAuth(popup:Window){return new Promise<string>((resolve,reject)=>{
 let poll:number|undefined;const cleanup=()=>{window.removeEventListener('message',message);if(poll!==undefined)window.clearInterval(poll);window.clearTimeout(timeout);};
 const message=(event:MessageEvent)=>{if(event.origin!==window.location.origin||event.source!==popup||event.data?.connectorId!=='github')return;if(event.data.type!=='appUserConnectorOAuthComplete'&&event.data.type!=='appUserConnectorOAuthFailed')return;cleanup();if(event.data.type==='appUserConnectorOAuthComplete'&&typeof event.data.code==='string')resolve(event.data.code);else reject(new Error('لم يكتمل الاتصال؛ تحقق من تفعيل الوصول دون اتصال في إعداد GitHub.'));};
 const timeout=window.setTimeout(()=>{cleanup();popup.close();reject(new Error('انتهت مهلة الاتصال؛ حاول مجدداً.'));},300000);
 window.addEventListener('message',message);poll=window.setInterval(()=>{if(popup.closed){cleanup();reject(new Error('أُغلقت نافذة الاتصال قبل إكماله.'));}},500);
});}
function GithubPage(){
 const qc=useQueryClient();const browse=useServerFn(browseGithub);const start=useServerFn(startGithubConnect);const complete=useServerFn(completeGithubConnection);const disconnect=useServerFn(disconnectGithub);
 const [example,setExample]=useState(false);const [repo,setRepo]=useState<GithubItem|null>(null);const [view,setView]=useState<'files'|'commits'>('files');const [path,setPath]=useState('');const [ref,setRef]=useState('');const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [connecting,setConnecting]=useState(false);
 const query=useQuery({queryKey:['github',repo?.owner,repo?.name,view,path,ref,page],queryFn:()=>browse({data:{view:repo?view:'repos',owner:repo?.owner,repo:repo?.name,path,ref,page}}),enabled:!example});
 const data=query.data;const connected=data?.connected??false;const items=example?(repo?(view==='commits'?EXAMPLE_COMMITS:EXAMPLE_FILES):[EXAMPLE_REPO]):data?.items??[];
 const rawContent=example&&repo&&path?EXAMPLE_CONTENT[path]:undefined;
 let fileText=rawContent??'';if(!example&&data?.content){try{fileText=data.content.encoding==='base64'?new TextDecoder().decode(Uint8Array.from(atob(data.content.value.replace(/\s/g,'')),c=>c.charCodeAt(0))):data.content.value;}catch{fileText='تعذر عرض محتوى الملف.';}}
 const isFile=Boolean(rawContent!==undefined||(!example&&data?.content));
 function selectRepo(item:GithubItem){setRepo(item);setRef(item.ref??'main');setPath('');setPage(1);}
 async function connect(){const popup=window.open('','azcodex-github','width=600,height=720');if(!popup){toast.error('اسمح بالنوافذ المنبثقة ثم حاول مجدداً.');return;}setConnecting(true);try{const {authorizationUrl}=await start();const pending=waitForOAuth(popup);popup.location.href=authorizationUrl;const code=await pending;await complete({data:{code}});setExample(false);setRepo(null);await qc.invalidateQueries({queryKey:['github']});toast.success('تم ربط GitHub بنجاح.');}catch(e){popup.close();toast.error(e instanceof Error?e.message:'تعذر الاتصال.');}finally{setConnecting(false);}}
 return <IntegrationShell><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="flex items-center gap-3 text-3xl font-semibold"><Github className="size-8"/>GitHub</h1><p className="mt-2 text-sm text-muted-foreground">{example?'مثال العزب التجريبي — لا يمثل مستودعاً حقيقياً':connected?'حسابك متصل':'حسابك غير متصل'}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>{setExample(!example);setRepo(null);setPath('');setPage(1);}}>{example?'مستودعاتي':'مثال العزب'}</Button><Button disabled={connecting} onClick={connect}><Github/>{connecting?'جارٍ الاتصال…':data?.reconnectRequired?'إعادة ربط GitHub':'ربط GitHub'}</Button>{connected&&!example&&<Button variant="outline" size="icon" title="فصل GitHub" aria-label="فصل GitHub" onClick={async()=>{try{await disconnect();setRepo(null);await qc.invalidateQueries({queryKey:['github']});toast.success('تم فصل GitHub.');}catch(e){toast.error(e instanceof Error?e.message:'تعذر الفصل.');}}}><Unplug/></Button>}</div></div>
 {query.error&&!example&&<p role="alert" className="mt-5 break-words text-sm text-destructive">{query.error.message}</p>}
 {data?.reconnectRequired&&!example&&<p className="mt-4 text-sm text-destructive">يلزم تجديد وصول حسابك إلى GitHub.</p>}
 <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-y border-border py-4"><div className="flex min-w-0 flex-wrap items-center gap-3">{repo&&<Button variant="ghost" size="icon" title="كل المستودعات" aria-label="كل المستودعات" onClick={()=>{setRepo(null);setPath('');setPage(1);}}><ArrowRight/></Button>}<h2 dir={repo?'ltr':'rtl'} className="break-all font-mono text-lg">{repo?.label??'المستودعات'}</h2></div>{repo?<div className="flex flex-wrap gap-2"><Input aria-label="الفرع" dir="ltr" className="w-36" value={ref} disabled={example} onChange={e=>{setRef(e.target.value);setPath('');setPage(1);}}/><Tabs value={view} onValueChange={v=>{setView(v as 'files'|'commits');setPath('');setPage(1);}}><TabsList><TabsTrigger value="files"><FileCode className="mr-1 size-4"/>الملفات</TabsTrigger><TabsTrigger value="commits"><GitCommitHorizontal className="mr-1 size-4"/>الالتزامات</TabsTrigger></TabsList></Tabs></div>:<Input aria-label="بحث المستودعات" placeholder="بحث المستودعات" className="max-w-xs" value={search} onChange={e=>setSearch(e.target.value)}/>}</div>
 {path&&<div className="mt-4 flex items-center gap-3"><Button variant="ghost" size="sm" onClick={()=>setPath(path.split('/').slice(0,-1).join('/'))}><Folder/>رجوع</Button><span dir="ltr" className="break-all font-mono text-sm">{path}</span></div>}
 {query.isPending&&!example?<p className="py-10 text-muted-foreground">جارٍ تحميل المستودعات…</p>:isFile?<pre dir="ltr" className="mt-5 max-h-[32rem] overflow-auto rounded-md border border-border bg-muted p-5 text-left text-sm"><code>{fileText||'لا يتوفر عرض نصي لهذا الملف.'}</code></pre>:<div className="divide-y divide-border">{items.filter(item=>repo||item.name.toLowerCase().includes(search.toLowerCase())).map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-5">{repo&&view==='commits'?<div><p className="whitespace-pre-wrap font-medium">{item.name}</p><p className="mt-2 text-xs text-muted-foreground">{item.label} · {item.description} {item.date?new Date(item.date).toLocaleString('ar'):''}</p></div>:<Button variant="ghost" className="h-auto min-w-0 max-w-full justify-start whitespace-normal text-start" onClick={()=>repo?setPath(item.path??''):selectRepo(item)}>{repo?(item.type==='dir'?<Folder className="shrink-0"/>:<FileCode className="shrink-0"/>):<Github className="shrink-0"/>}<span dir="ltr" className="break-all">{item.label??item.name}</span>{item.private&&<LockKeyhole className="size-3 shrink-0"/>}</Button>}{!repo&&<p className="w-full text-sm text-muted-foreground">{item.description}</p>}</div>)}</div>}
 {!isFile&&items.length===0&&!query.isPending&&<p className="py-10 text-center text-muted-foreground">{connected?'لا توجد نتائج.':'اربط حساب GitHub أو افتح مثال العزب.'}</p>}
 {!example&&(connected||query.error)&&<div className="mt-6 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>query.refetch()}><RefreshCw/>تحديث</Button>{(!repo||view==='commits')&&<><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>السابق</Button><span className="self-center text-sm">{page}</span><Button variant="outline" disabled={items.length<30} onClick={()=>setPage(p=>p+1)}>التالي</Button></>}</div>}
 </IntegrationShell>;
}